### ISSUE TITLE
[FEATURE] Guild Signatures

### ISSUE THREAD

**Issue by TheNullicorn** [MaxKorlaar/hypixel-signatures#13]
**Is your feature request related to a problem? Please describe.**
As far as I've seen, there aren't any Hypixel signature generators that target guilds and guild-related stats. Some guilds design custom banners that can be placed in their members' signatures as a means of advertising, but I have yet to see any dynamic guild banners that can be used on the forums.

**Describe the solution you'd like**
The image would be very similar to the "General statistics" generator (non-tooltip) that you currently have set up. In place of a player preview, there would be the guild's banner (provided through the [guild endpoint](https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/guild.md)). In terms of statistics, here's a few that I feel are worth including:
- Guild Name (and tag)
- Guild master's username
- Guild level progress (a mini version of the [player level progress](https://hypixel.maxkorlaar.com/status-sig/get-exp-circle/8614fb2de71d467595dcd7da3d977eae?color=1&animated) image on your old site?)
- Member count (`N / 125`)
- Legacy guild rank (also available via guild endpoint)
- Guild description (if it fits)
- Most active games (determined by sorting `guild.guildExpByGameType` values in guild endpoint)

**Additional context**
I made a quick mockup earlier just to get a feel for the layout. It includes a couple of the above stats as well as just general placement; ignore the color scheme.

![Untitled](https://user-images.githubusercontent.com/64789500/82955042-f9440600-9f7b-11ea-9a2d-b03d031039df.png)

**Comment by MaxKorlaar** [comment]
Thanks for the suggestion!
