### ISSUE TITLE
[FEATURE] Use consistent formatting for numbers

### ISSUE THREAD

**Issue by TheNullicorn** [MaxKorlaar/hypixel-signatures#19]
**Is your feature request related to a problem? Please describe.**
This isn't a big deal, but I noticed that currently "Karma" appears to be the only statistic displayed using commas (it was also the only field changed to do this in #4).

**Describe the solution you'd like**
I personally prefer the use of commas because they make it easier to read stats while glancing over someone's signature. I propose using number_format() on all non-percentage numbers (including network level since now there's players like [this](https://hypixel.paniek.de/signatures#LegoBlokkkkk)).

**Additional context**
Current formatting:
![Screen Shot 2020-05-28 at 4 19 41 PM](https://user-images.githubusercontent.com/64789500/83189694-59af8080-a0ff-11ea-9e0a-1727f2bec87f.png)
![Screen Shot 2020-05-28 at 4 20 08 PM](https://user-images.githubusercontent.com/64789500/83189695-5a481700-a0ff-11ea-9438-2d905575873a.png)
![Screen Shot 2020-05-28 at 4 21 00 PM](https://user-images.githubusercontent.com/64789500/83189699-5a481700-a0ff-11ea-8f63-216c4ec315a0.png)
_(notice how commas are only used for karma values, which look a bit out of place)_

**Comment by MaxKorlaar** [comment]
Good point, this should indeed be more consistent. Will be fixed together with #18 soon :)
